const contacts = [
  {
    id: 1,
    firstName: "דנה",
    lastName: "כהן",
    phone: "050-1234567",
    relation: "חברה",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 2,
    firstName: "יוסי",
    lastName: "לוי",
    phone: "052-7654321",
    relation: "בן משפחה",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 3,
    firstName: "נופר",
    lastName: "עמר",
    phone: "053-0000000",
    relation: "חברה מהעבודה",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 4,
    firstName: "רועי",
    lastName: "בן דוד",
    phone: "054-2223333",
    relation: "חבר מהעבודה",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 5,
    firstName: "הילה",
    lastName: "פרידמן",
    phone: "050-6547890",
    relation: "חברה",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: 6,
    firstName: "משה",
    lastName: "קרן",
    phone: "058-1239876",
    relation: "חבר",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 7,
    firstName: "שני",
    lastName: "ירון",
    phone: "052-7655555",
    relation: "חברה מהעבודה",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 8,
    firstName: "דוד",
    lastName: "סוויסה",
    phone: "050-8765432",
    relation: "בן משפחה",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: 9,
    firstName: "אורית",
    lastName: "מזרחי",
    phone: "053-3334444",
    relation: "חברה",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
  },
  {
    id: 10,
    firstName: "גיל",
    lastName: "ברק",
    phone: "054-4442222",
    relation: "חבר",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    id: 11,
    firstName: "טל",
    lastName: "שחר",
    phone: "055-1122334",
    relation: "חבר מהעבודה",
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: 12,
    firstName: "נועה",
    lastName: "אלקיים",
    phone: "052-3344556",
    relation: "חברה",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    firstName: "עומר",
    lastName: "שטרן",
    phone: "058-9988776",
    relation: "חבר",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
  },
];

export default contacts;
